export function eventCountryToGeologyCountry(eventCountry: string) {
  return a[eventCountry] || eventCountry;
}

const a: { [eventCountry: string]: string | undefined } = {
  "Dominican Republic": "Dominican Rep.",
  "United States": "United States of America",
  "East Germany (GDR)": "Germany",
  "West Germany (FRG)": "Germany",
  "South Yemen": "Yemen",
  "West Bank and Gaza Strip": "West Bank and Gaza Strip",
//   Czechoslovakia: "Czechoslovakia",
  "South Vietnam": "Vietnam",
//   Zaire: "Zaire",
  "People's Republic of the Congo": "Congo",
//   Yugoslavia: "Yugoslavia",
//   Singapore: "Singapore",
  "North Yemen": "Yemen",
//   Andorra: "Andorra",
//   Barbados: "Barbados",
//   Malta: "Malta",
//   Rhodesia: "Rhodesia",
  "Soviet Union": "Russia",
  "Western Sahara": "Western Sahara",
//   Bahrain: "Bahrain",
  "Hong Kong": "China",
//   Grenada: "Grenada",
//   "New Hebrides": "New Hebrides",
//   Guadeloupe: "Guadeloupe",
//   Martinique: "Martinique",
  "Vatican City": "Italy",
  "Central African Republic": "Central African Rep.",
//   Seychelles: "Seychelles",
  Dominica: "Dominican Rep.",
//   Swaziland: "Swaziland",
//   "French Guiana": "French Guiana",
  "Falkland Islands": "Falkland Is.",
//   Maldives: "Maldives",
//   Mauritius: "Mauritius",
  "Republic of the Congo": "Dem. Rep. Congo",
//   "Ivory Coast": "Ivory Coast",
//   "Antigua and Barbuda": "Antigua and Barbuda",
  "Bosnia-Herzegovina": "Bosnia and Herz.",
  "Equatorial Guinea": "Eq. Guinea",
//   Comoros: "Comoros",
  "Slovak Republic": "Slovakia",
//   "Wallis and Futuna": "Wallis and Futuna",
  "Czech Republic": "Czechia",
//   "St. Kitts and Nevis": "St. Kitts and Nevis",
//   "French Polynesia": "French Polynesia",
  Macau: "China",
  "Democratic Republic of the Congo": "Dem. Rep. of the Congo",
  "Solomon Islands": "Solomon Is.",
//   "East Timor": "East Timor",
//   "St. Lucia": "St. Lucia",
//   International: "International",
//   "Serbia-Montenegro": "Serbia-Montenegro",
  "South Sudan": "S. Sudan",
};
